apiVersion: apps/v1
kind: Deployment
metadata:
  name: q-read
  namespace: security
spec:
  replicas: 2  # Increased replicas for high availability
  selector:
    matchLabels:
      app: q-read
  template:
    metadata:
      labels:
        app: q-read
    spec:
      serviceAccountName: my-sqs-read-msgs
      automountServiceAccountToken: false
      containers:
      - name: q-read
        image: 844933341824.dkr.ecr.us-east-1.amazonaws.com/keda-pod-identity-registry:latest
        resources:
          limits:
            cpu: "500m"  # Add CPU limit
            memory: "128Mi"  # Increase memory limit
          requests:
            cpu: "250m"
            memory: "64Mi"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-sqs-read-msgs
  namespace: security

